lsi: false
safe: true
source: [./]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
google_analytics:
theme: jekyll-theme-minimal
title: [Ákos Makács]
# logo: /assets/img/logo.png
description: [iOS Application Engineer | Data Science MSc Student | Amsterdam-NL]
plugins:
  - jekyll-seo-tag
navigation:
  - title: Home
    url: '/'
  - title: About Me
    url: '/about-me/'