lsi: false
safe: true
source: [./]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: jekyll-theme-minimal
title: [Ákos Makács]
description: [iOS Application Engineer | Data Science MSc Student | Amsterdam, NL ]